language: python
sudo: false

python:
  - '2.6'
  - '2.7'
  - '3.4'
  - '3.5'

matrix:
  exclude:
  - python: '2.6'
    env: DJANGO_VERSION=1.7.x
- python: '2.6'
    env: DJANGO_VERSION=1.8.x
  - python: '3.5'
    env: DJANGO_VERSION=1.7.x
  - python: '3.5'
    env: DJANGO_VERSION=1.6.x

env:
  - DJANGO_VERSION=1.8.x
  - DJANGO_VERSION=1.7.x
  - DJANGO_VERSION=1.6.x

install:
  - pip install tox

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"

after_success:
  - pip install "coveralls==0.4.1" coverage
  - coverage report
  - coveralls
